version: '2'

services:
#  web:
#    build: .
#    links:
#      - nginx
#      - db
#      - redis
#      - php:php

# NGINX
  web:
    restart: always
    image: nginx:stable
    ports:
      - "80:80"
    links:
      - php
    volumes_from:
      - php:ro
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/magento.conf:/etc/nginx/conf.d/magento.conf
      - ./conf/nginx/xhgui.conf:/etc/nginx/conf.d/xhgui.conf


# PHP
  php:
#    image: php:7.1-fpm
    build:
      context: ./php55
      args:
        php_ext: bcmath curl dom json iconv intl mbstring mcrypt opcache pdo pdo_mysql session simplexml soap sockets xml xmlrpc xsl zip
    command: bash -c "service ssh stop && service ssh start"
    links:
      - redis
      - db
      - mailcatcher
      - mongo # we need it for xhprof
    volumes:
      - ../src:/var/www/magento
      - ./conf/smtp/msmtprc:/etc/msmtprc
      - ./conf/magento/app/etc/local.xml:/var/www/env/magento/app/etc/local.xml
      - ./php55/tools/xhgui:/var/www/xhgui # we need it for xhprof
      - ./conf/xhgui/config.php:/var/www/env/xhgui/config/config.php # we need it for xhprof
    ports:
      - "3333:22"


# CACHES
  redis:
    image: redis


# DB
  db:
    image: mysql:5.6
#    image: mysql:5.7
#    image: mariadb:latest
    env_file:
      - ./conf/db/mysql.env
    volumes:
      - ./db/dump.sql:/root/dump.sql
      - ./db/tune.sql:/root/tune.sql
      - ./conf/db/.my.cnf:/root/.my.cnf
      - ./conf/db/etc/mysql/conf.d/:/etc/mysql/conf.d/

# Email
  mailcatcher:
    image: schickling/mailcatcher
    expose:
      - 1025
    ports:
      - "1080:1080"

# OTHERS
  mongo:
    image: mongo:3.2
