version: '2'

services:

# NGINX
  web:
    container_name: m1_web_11
    restart: always
    image: nginx:stable
    ports:
      - "80:80"
    links:
      - php
      - solr
    networks:
      default:
        aliases:
          - "www.magento.local"
    volumes_from:
      - php:ro
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/magento.conf:/etc/nginx/conf.d/magento.conf:ro
      - ./conf/nginx/xhgui.conf:/etc/nginx/conf.d/xhgui.conf:ro


# PHP
  php:
    container_name: m1_php_11
    build:
      context: ./php55
      args:
        php_ext: bcmath curl dom json iconv intl mbstring mcrypt opcache pdo pdo_mysql session simplexml soap sockets xml xmlrpc xsl zip
#    command: bash -c "service ssh stop && service ssh start"
    links:
      - redis
      - db
      - mailcatcher
      - mongo # we need it for xhprof
      - solr
    volumes:
      - ../src:/var/www/magento
      - ./conf/smtp/msmtprc:/etc/msmtprc:ro
      - ./conf/magento/app/etc/local.xml:/var/www/env/magento/app/etc/local.xml:ro
      - ./tools/restore/restore.sh:/usr/local/bin/restore.sh:ro
      - ./tools/restore/restore.conf:/usr/local/bin/.restore.conf:ro
      - ./php55/tools/xhgui:/var/www/xhgui # we need it for xhprof
      - ./conf/xhgui/config.php:/var/www/env/xhgui/config/config.php:ro # we need it for xhprof
    ports:
      - "3333:22"


# CACHES
  redis:
    container_name: m1_redis_11
    image: redis
    volumes:
      - ./data/redis:/data


# DB
  db:
    container_name: m1_db_11
    image: mysql:5.6
#    image: mysql:5.7
#    image: mariadb:latest
    env_file:
      - ./conf/db/mysql.env
    volumes:
      - ./data/db/data:/var/lib/mysql
      - ./data/db/logs/mysql:/var/log/mysql
      - ./db/dump.sql:/root/dump.sql:ro
      - ./db/tune.sql:/root/tune.sql:ro
      - ./conf/db/.my.cnf:/root/.my.cnf:ro
      - ./conf/db/etc/mysql/conf.d/:/etc/mysql/conf.d/


# Search engines
  solr:
    container_name: m1_solr_11
    build:
      context: ./solr36
      args:
        SOLR_VERSION: "3.6.2"
        SOLR_KEY: "322D7ECA"
        SOLR_SOURCE_SHA256_HASH: "3a1a40542670ea6efec246a081053732c5503ec1"
    ports:
      - "8983:8983"


# Email
  mailcatcher:
    container_name: m1_mailcatcher_11
    image: schickling/mailcatcher
    expose:
      - 1025
    ports:
      - "1080:1080"

# OTHERS

# We need Mongo for xhprof
  mongo:
    container_name: m1_mongo_11
    image: mongo:3.2
